apiVersion: apps/V1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: apache
  spec:
    replicas: 5
    selector:
      matchlabels:
        app: apache
    template:
      metadata:
        labels:
         app: apache
      spec:
        containers: mydeployment
        image: ilamparidhi/prt-task:latest
        ports:
         - containerPort: 80
